#!/bin/bash
set -eu

HOSTNAME=$1
CPU=$2
MEM=$3
DISK=$4

for MAC in $MACS; do
    nova baremetal-node-create $HOSTNAME $CPU $MEM $DISK $MAC
    sleep 5
done
date
echo "Nodes will be available in 60 seconds from now."
